# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user_score', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('comp_score', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
        ),
    ]
