# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='comp_score',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_score',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
