# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171117_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='comp_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
