# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20171117_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='hard_count',
            field=models.IntegerField(default=0),
        ),
    ]
