# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_username_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
